### PR TITLE
Add "sections comments" checkbox

### PR DESCRIPTION
**Pull request by d9k**
Selection_2024-07-04_01-22-20_01

### CODE REVIEW

**Comment by abdul-alhasany** [comment]
What does this pull request do? Can you provide more context.

**Comment by d9k** [comment]
> What does this pull request do? Can you provide more context.

Adds checkbox to remove section comments from output (like `// Methods`)

**Comment by abdul-alhasany** [comment]
I updated the style and the UI. I think checkbox is taking too much space. So I added a toolbar that will appear after the code is converted.

**Comment by d9k** [comment]
@abdul-alhasany, thanks for your work!

**Pull request merged**
