### PR TITLE
extract code from <script> tag automatically

### PR DESCRIPTION
**Pull request by d9k**
I'm in a hurry, had to disable come ESLint rules. Feel free to edit.

### CODE REVIEW

**Comment by abdul-alhasany** [comment]
Thanks for contributing again. It is almost never a good idea to use regex to parse xml (or html). There are many edge cases that need to be accounted for, which is a big task in itself.

As for pull requests please note:
- It is better to create an issue first to discuss if this is something that can be implemented. 
- For new features, we need to make sure current tests are running successfully.
- We also need new test tests to make sure the code does not break in future pull requests.

Thanks again but I will close this pull request for now.

**Comment by d9k** [comment]
@abdul-alhasany, ok, but in my opinion temporary suboptimal regex solution is better than nothing :grin: 

> We also need new test tests to make sure the code does not break in future pull requests.

That's a good point

**Comment by d9k** [comment]
I'm not sure whether we need to think about edge cases much. Everyone use `prettier` these days. My solution just expect `<script ...>` and `</script >` to be on the separate lines. Also we can programmatically pass through `prettier` again to ensure this expectation.

**Comment by abdul-alhasany** [comment]
The code already runs eslint on the output. I try to balance between the benefit gained vs the work that needs to be done for this feature.

A user can copy/paste the code between `<script></script>` tags as easily as copying the whole code. So there is not much developer experience gained given the work that needs to be done to implement this feature.

Either way, this is not planned for now but hopefully in future versions.

**Comment by d9k** [comment]
> A user can copy/paste the code between `<script></script>` tags as easily as copying the whole code

Actually it's pretty frustrating on nth time in a day. But I'm ok using my patched fork of your tool :)

> the work that needs to be done to implement this feature

As I said the edge cases are too rare. Also to eliminate these rare cases: prettier runs very fast, faster then eslint. Definitely faster then selecting code inside `<script>` tag manually

**Comment by abdul-alhasany** [comment]
@d9k Try this: https://tools.kalimah-apps.com/vue-composition-converter/

**Pull request closed without merging**
